workflows:
  my-workflow:
    environment:
      groups:
        - test
    scripts:
      - name: Add provisioning profiles
        script: |
          set -e # exit on first failed command

          PROFILES_HOME="$HOME/Library/MobileDevice/Provisioning Profiles"
          mkdir -p "$PROFILES_HOME"
          echo ${PROVISIONING_PROFILE?} | base64 --decode > "$PROFILES_HOME/$(uuidgen).mobileprovision"
      - name: Set up code signing settings on Xcode project
        script: xcode-project use-profiles
      - name: Add signing certificate
        script: |
          set -e # exit on first failed command
      - name: Build ipa for distribution
        script: xcode-project build-ipa
                    --workspace "${XCODE_WORKSPACE?}"
    artifacts:
      - build/ios/ipa/*.ipa
