workflows:
  my-workflow:
    scripts:
      - name: Run iOS tests
        script: |
          set -e # exit on first failed command

          xcode-project run-tests \
              --device "iPhone 12"
        test_report: build/ios/test/*.xml
